// src/components/TransactionForm.tsx
import React from 'react';
import { useState } from 'react';

interface Props {
    onAdd: (text: string, amount: number) => void;
}

export const TransactionForm = ({ onAdd }: Props) => {
    const [text, setText] = useState('');
    const [amount, setAmount] = useState('');

    const onSubmit = (e: React.FormEvent) => {
        e.preventDefault();

        if(text.trim() && amount !== '') {
            alert("Please enter the text and amount of money.");
            return;
        }

        onAdd(text, +amount);

        setText('');
        setAmount('');
    };
    
}

// src/components/TransactionForm.vue
<script setup lang="ts">
import { ref } from 'vue';

const emit = defineEmits<{
  (e: 'addTransaction', text: string, amount: number): void
}>();

const text = ref('');
const amount = ref<number | null>(null);

const onSubmit = () => {
  if (!text.value || amount.value === null) {
    alert('Please add a text and amount');
    return;
  }

  emit('addTransaction', text.value, amount.value);

  text.value = '';
  amount.value = null;
};
</script>
